DROP TABLE T_TEMPLATE_ACCOUNT;

CREATE TABLE T_TEMPLATE_ACCOUNT(
       PK_T_TEMPLATE_ACCOUNT_ID           NUMBER(10) NOT NULL PRIMARY KEY,
       TEMPLATE_ID     VARCHAR2(100) NOT NULL,
       ACCOUNT_NAME    VARCHAR2(100) NOT NULL,
       ACCOUNT_PASSWORD VARCHAR2(20) NOT NULL,
       ACCOUNT_TYPE     VARCHAR2(1) NOT NULL,
       CREATED_BY       VARCHAR2(50)            NOT NULL,
       CREATED_ON       TIMESTAMP                    NOT NULL,
       MODIFIED_BY      VARCHAR2(50)            ,
       MODIFIED_ON      TIMESTAMP                   
);
