
ALTER TABLE T_EQUIPMENTEVENT  DROP PRIMARY KEY CASCADE;

DROP TABLE T_EQUIPMENTEVENT CASCADE CONSTRAINTS;

CREATE TABLE T_EQUIPMENTEVENT 
(
   PK_EQUIEVENT_ID      NUMBER                         NOT NULL PRIMARY KEY,
   SERIALNUMBER         VARCHAR2(200)                  NOT NULL,
   EVENTTYPE            VARCHAR2(200)                  NOT NULL,
   EVENTSTATUS          INT                            NOT NULL,
   EQUIPMENTTYPE		INT							   NULL,
   CREATED_BY           VARCHAR(60)                    NOT NULL,
   CREATED_ON           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
   MODIFIED_BY          VARCHAR(60)                    NULL,
   MODIFIED_ON          TIMESTAMP DEFAULT SYSTIMESTAMP NULL,
   DESCRIPT             VARCHAR2(200)                  NULL
);

COMMENT ON TABLE T_EQUIPMENTEVENT IS 
'设备事件';

COMMENT ON COLUMN T_EQUIPMENTEVENT.EVENTTYPE IS 
'1.增加物理机
2.移除物理机
3.变化位置
4物理机状态变化';
COMMENT ON COLUMN T_EQUIPMENTEVENT.EVENTSTATUS IS 
'事件状态：
1-----待处理；
2-----己处理；
3-----关闭；';
comment on column T_EQUIPMENTEVENT.EQUIPMENTTYPE is 'x86机架式服务器--1;x86刀片服务器--2;hp小型机--3;x86刀箱-4';
