ALTER TABLE APP_CONFIG
 DROP PRIMARY KEY CASCADE;
DROP TABLE APP_CONFIG CASCADE CONSTRAINTS;

CREATE TABLE APP_CONFIG
(
  PK_APP_CONFIG_ID  NUMBER(19)          NOT NULL,
  CONFIG_KEY    VARCHAR2(255)           NOT NULL,
  CONFIG_VALUE  VARCHAR2(255),
  DESCRIPTION   VARCHAR2(255),
  CREATED_BY    VARCHAR2(50)            NOT NULL,
  CREATED_ON    TIMESTAMP                    NOT NULL,
  MODIFIED_BY   VARCHAR2(50)            NOT NULL,
  MODIFIED_ON   TIMESTAMP                    NOT NULL
)
;
ALTER TABLE APP_CONFIG
ADD CONSTRAINT APP_CONFIG_PK PRIMARY KEY
(
PK_APP_CONFIG_ID
)
 ENABLE
;
