
ALTER TABLE T_EQUIPMENTENROLL  DROP PRIMARY KEY CASCADE;

DROP TABLE T_EQUIPMENTENROLL CASCADE CONSTRAINTS;

CREATE TABLE T_EQUIPMENTENROLL 
(
   PK_EQUENROLL_ID      NUMBER                         NOT NULL PRIMARY KEY,
   TARGET_TYPE          NUMBER(2)                      NOT NULL,
   IP                   VARCHAR2(200)                  NULL,
   DESCRIPT             VARCHAR2(200)                  NULL,
   AVAILABLE            NUMBER(1)   DEFAULT 1          NOT NULL,
   CREATED_BY           VARCHAR(60)                    NOT NULL,
   CREATED_ON           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
   MODIFIED_BY          VARCHAR(60)                    NULL,
   MODIFIED_ON          TIMESTAMP DEFAULT SYSTIMESTAMP NULL
);

COMMENT ON TABLE T_EQUIPMENTENROLL IS 
'自动发现的目标  注册表';

COMMENT ON COLUMN T_EQUIPMENTENROLL.TARGET_TYPE IS 
'0:X86机架式服务器
1:X86刀片服务器  
7:刀箱                    待讨论
8:HP小型机
';

COMMENT ON COLUMN T_EQUIPMENTENROLL.IP IS 
'自动发现的目标IP';

COMMENT ON COLUMN T_EQUIPMENTENROLL.AVAILABLE IS 
'是否启动扫描
开启1
关闭0';
