
ALTER TABLE T_RESOURCE  DROP PRIMARY KEY CASCADE;

DROP TABLE T_RESOURCE CASCADE CONSTRAINTS;

CREATE TABLE T_RESOURCE 
(
   T_RESOURCE_ID        NUMBER                         NOT NULL PRIMARY KEY,
   CPU                  VARCHAR2(200)                  NOT NULL,
   MEMORY               VARCHAR2(200)                  NOT NULL,
   TYPE                 INT                            NOT NULL,
   AMOUNT               INT                            NOT NULL,
   RESOURCEPOOLID       VARCHAR2(200)                  NOT NULL,
   CREATED_BY           VARCHAR(60)                    NOT NULL,
   CREATED_ON           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
   MODIFIED_BY          VARCHAR(60)                    NULL,
   MODIFIED_ON          TIMESTAMP DEFAULT SYSTIMESTAMP NULL
);

COMMENT ON TABLE T_RESOURCE IS 
'X86或HPVM统计数据';

COMMENT ON COLUMN T_RESOURCE.CPU IS 
'CPU数量';

COMMENT ON COLUMN T_RESOURCE.TYPE IS 
'资源类型：
1：X86物理机
2：HPVM';

COMMENT ON COLUMN T_RESOURCE.AMOUNT IS 
'X86 或虚机台数';

COMMENT ON COLUMN T_RESOURCE.RESOURCEPOOLID IS 
'资源池ID';
