REM Populate some seed data into the IAAS tables

REM $Id: populateSchemaTables.sql,v 1.5 2013/12/28 17:33:02 Zhefang Chen Exp $

spool _populate_schema_tables.log

--Insert into app_config values (-1,128723, 'HD Television','A High-Definition Flat Screen Television that uses DLP Technology.', 'Video', 1999.99, 'Azimuth', null, 'images/hd-tv-sm.jpg' );

PROMPT 初始化TABLE T_ResourcePool  一级资源池数据
INSERT INTO T_ResourcePool(PK_T_ResourcePool_ID,resourcepool_id,Name,descript,Created_By,modified_by) VALUES(1,'R_01','生产池','该池用于生产','admin','admin');
INSERT INTO T_ResourcePool(PK_T_ResourcePool_ID,resourcepool_id,Name,descript,Created_By,modified_by) VALUES(2,'R_02','测试池','该池用于测试','admin','admin');


PROMPT 初始化TABLE APP_CONFIG 数据
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'getExternalValue.no', '0', '不需要从外部得到值', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'getExternalValue.yes', '1', '从外部得到值', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'approvalAction.reject', '0', '拒绝', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'approvalAction.approve', '1', '审批通过', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'editable.false', '0', '不可修改', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'editable.true', '1', '可以修改', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'visible.hidden', '0', '隐藏', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'visible.expose', '1', '显示', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'resourcetype.secondarystorage', '7', '辅助存储', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'resourcetype.primarystorage', '6', '主存储', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'resourcetype.host', '5', '主机', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'resourcetype.cluster', '4', '集群', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'resourcetype.pod', '3', 'pod', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'resourcetype.zone', '2', 'zone', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'resourcetype.resoucepool', '1', '一级资源池', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);

INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'workorder_status.waitingforapproval', '1', '待审批', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'workorder_status.approved', '2', '审批通过待处理', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'workorder_status.rejected', '3', '审批未通过', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'workorder_status.provisioning', '4', '审批通过正在处理', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'workorder_status.provisionsucceed', '5', '处理成功', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'workorder_status.provisonfail', '6', '处理失败', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);

INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'resourcepool_permission.reject', '0', '拒绝', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'resourcepool_permission.permit', '1', '允许', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'resourcepool_related_object_type.project', '3', '项目', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'resourcepool_related_object_type.domain', '2', '域', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'resourcepool_related_object_type.account', '1', '账户', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'approve_type.auto_approval', '2', '自动审批', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'approve_type.manual_approval', '1', '人工审批', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'workorder_type.newVolume', '7', '新建卷', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'workorder_type.scaleVirtualmachine', '6', '更改服务方案', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'workorder_type.deployVirtualMachine', '5', '添加实例', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL, 'workorder_type.accountLimitapplication', '4', '账户扩容申请', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'workorder_type.domainLimitapplication', '3', '域扩容申请', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'workorder_type.projectLimitapplication', '2', '项目扩容申请', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'workorder_type.newProjectapplication', '1', '项目申请', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'workorder_type.X86PhysicalResourcesApplication', '8', 'X86物理资源申请', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);
INSERT INTO APP_CONFIG (PK_APP_CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON)
VALUES (T_LOG_ID_SEQ.NEXTVAL,'workorder_type.HPMinicomputerResourcesApplication', '9', 'HP小型机资源申请', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP);


PROMPT 初始化TABLE T_PROVISION_ATTRIBUTE  
PROMPT 初始化项目申请属性
INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'memory', 'int', '', 1, 0, 1, 14, '最大内存（MiB）', 'Total Memory (in MB) a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'cpu', 'int', '', 1, 0, 1, 13, '最大CPU内核数', 'Total number of CPU cores a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'vpc', 'int', '', 1, 0, 1, 12, '最大VPC数', 'Number of VPC a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'network', 'int', '', 1, 0, 1, 11, '最大网络数', '', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'template', 'int', '', 1, 0, 1, 10, '最大模板数', 'Number of templates that a user can register/create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'snapshot', 'int', '', 1, 0, 1, 9, '最大快照数', 'Number of snapshots a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'volume', 'int', '', 1, 0, 1, 8, '最大卷数', 'Number of disk volumes a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'ip', 'int', '', 1, 0, 1, 7, '最大公用IP数', '    ', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'instance', 'int', '', 1, 0, 1, 6, '最大用户VM数', 'Number of instances a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'resourcePoolId', 'enum', '', 1, 1, 1, 5, '资源池', '', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'displaytext', 'text', '', 1, 0, 1, 2, '显示文本', 'name of the project', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'name', 'text', '', 1, 0, 1, 1, '项目名称', 'display text of the project', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'primaryStorage', 'int', '', 1, 0, 1, 15, '最大主存储（GiB）', 'Total primary storage space (in GiB) a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'secondaryStorage', 'int', '', 1, 0, 1, 16, '最大辅助存储(GiB)', 'Total secondary storage space (in GiB) a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newProjectapplication'), 'applyReason', 'text', '', 1, 0, 0, 17, '申请理由', '申请理由', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

PROMPT 初始化项目扩容属性
INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'projectid', 'text', '', 1, 1, 0, 1, '项目名称', '', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'instance', 'int', '', 1, 0, 1, 2, '最大用户VM数', '      Number of instances a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'ip', 'int', '', 1, 0, 1, 3, '最大公用IP数', '    ', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'volume', 'int', '', 1, 0, 1, 4, '最大卷数', '  Number of disk volumes a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'snapshot', 'int', '', 1, 0, 1, 5, '最大快照数', '  Number of snapshots a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'template', 'int', '', 1, 0, 1, 6, '最大模板数', '  Number of templates that a user can register/create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'network', 'int', '', 1, 0, 1, 7, '最大网络数', '', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'vpc', 'int', '', 1, 0, 1, 8, '最大VPC数', '  Number of VPC a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'cpu', 'int', '', 1, 0, 1, 9, '最大CPU内核数', '  Total number of CPU cores a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'memory', 'int', '', 1, 0, 1, 10, '最大内存（MiB）', '  Total Memory (in MB) a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'primaryStorage', 'int', '', 1, 0, 1, 11, '最大主存储（GiB）', '  Total primary storage space (in GiB) a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'secondaryStorage', 'int', '', 1, 0, 1, 12, '最大辅助存储(GiB)', 'Total secondary storage space (in GiB) a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.projectLimitapplication'), 'applyReason', 'text', '', 1, 0, 0, 13, '申请理由', '申请理由', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

PROMPT 初始化域扩容属性
INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'domainId', 'text', '', 1, 1, 0, 1, '域', '  domain ID of the account owning a project', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'instance', 'int', '', 1, 0, 1, 2, '最大用户VM数', '      Number of instances a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'ip', 'int', '', 1, 0, 1, 3, '最大公用IP数', '    ', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'volume', 'int', '', 1, 0, 1, 4, '最大卷数', '  Number of disk volumes a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'snapshot', 'int', '', 1, 0, 1, 5, '最大快照数', '  Number of snapshots a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'template', 'int', '', 1, 0, 1, 6, '最大模板数', '  Number of templates that a user can register/create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'network', 'int', '', 1, 0, 1, 7, '最大网络数', '', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'vpc', 'int', '', 1, 0, 1, 8, '最大VPC数', '  Number of VPC a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'cpu', 'int', '', 1, 0, 1, 9, '最大CPU内核数', '  Total number of CPU cores a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'memory', 'int', '', 1, 0, 1, 10, '最大内存（MiB）', '  Total Memory (in MB) a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'primaryStorage', 'int', '', 1, 0, 1, 11, '最大主存储（GiB）', '  Total primary storage space (in GiB) a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'secondaryStorage', 'int', '', 1, 0, 1, 12, '最大辅助存储(GiB)', 'Total secondary storage space (in GiB) a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.domainLimitapplication'), 'applyReason', 'text', '', 1, 0, 0, 13, '申请理由', '申请理由', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);


PROMPT 初始化租户扩容属性
INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'account', 'text', '', 1, 0, 0, 1, '账户', '  account who will be Admin for the project', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'domainId', 'text', '', 1, 1, 0, 2, '域', '  domain ID of the account owning a project', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'instance', 'int', '', 1, 0, 1, 3, '最大用户VM数', '      Number of instances a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'ip', 'int', '', 1, 0, 1, 4, '最大公用IP数', '    ', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'volume', 'int', '', 1, 0, 1, 5, '最大卷数', '  Number of disk volumes a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'snapshot', 'int', '', 1, 0, 1, 6, '最大快照数', '  Number of snapshots a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'template', 'int', '', 1, 0, 1, 7, '最大模板数', '  Number of templates that a user can register/create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'network', 'int', '', 1, 0, 1, 8, '最大网络数', '', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'vpc', 'int', '', 1, 0, 1, 9, '最大VPC数', '  Number of VPC a user can create.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'cpu', 'int', '', 1, 0, 1, 10, '最大CPU内核数', '  Total number of CPU cores a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'memory', 'int', '', 1, 0, 1, 11, '最大内存（MiB）', '  Total Memory (in MB) a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'primaryStorage', 'int', '', 1, 0, 1, 12, '最大主存储（GiB）', '  Total primary storage space (in GiB) a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'secondaryStorage', 'int', '', 1, 0, 1, 13, '最大辅助存储(GiB)', 'Total secondary storage space (in GiB) a user can use.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.accountLimitapplication'), 'applyReason', 'text', '', 1, 0, 0, 14, '申请理由', '申请理由', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);


PROMPT 初始化添加实例属性
INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'resourcePoolId', 'enum', '', 1, 1, 0, 1, '一级资源池', '', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'serviceofferingid', 'enum', '', 1, 1, 1, 2, '计算方案', 'the ID of the service offering for the virtual machine', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'templateid', 'enum', 'zoneid', 1, 1, 1, 4, '模板', 'the ID of the template for the virtual machine', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'zoneid', 'enum', 'resourcePoolId', 1, 1, 1, 3, '区域', 'availability zone for the virtual machine', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'diskofferingid', 'enum', '', 1, 1, 1, 6, '数据磁盘方案', 'the ID of the disk offering for the virtual machine. If the template is of ISO format, the diskOfferingId is for the root disk volume. Otherwise this parameter is used to indicate the offering for the data disk volume. If the templateId parameter passed is from a Template object, the diskOfferingId refers to a DATA Disk Volume created. If the templateId parameter passed is from an ISO object, the diskOfferingId refers to a ROOT Disk Volume created.', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'diskSize', 'int', '', 0, 0, 1, 7, '磁盘大小', '磁盘大小', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'displayname', 'text', '', 1, 0, 1, 8, 'VM名称 (可选)', 'an optional user generated name for the virtual machine', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,0);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'group', 'text', '', 1, 0, 1, 9, '添加到组 (可选)', 'an optional group for the virtual machine', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,0);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'hypervisor', 'text', '', 1, 0, 0, 10, '虚拟机管理程序', 'the hypervisor on which to deploy the virtual machine', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'name', 'text', '', 0, 0, 1, 11, 'Host名称 (可选)', 'host name for the virtual machine', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,0);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'networkids', 'enum', '', 1, 1, 1, 12, '网络', 'list of network ids used by virtual machine. Can''t be specified with ipToNetworkList parameter', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'projectid', 'text', '', 1, 1, 0, 13, '项目', 'Deploy vm for the project', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.deployVirtualMachine'), 'applyReason', 'text', '', 1, 0, 0, 14, '申请理由', '申请理由', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);



PROMPT 初始化更改服务方案属性

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.scaleVirtualmachine'), 'vmid', 'text', '', 1, 1, 0, 1, '虚机', 'The ID of the virtual machine', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.scaleVirtualmachine'), 'serviceofferingid', 'enum', '', 1, 1, 1, 2, '服务方案', 'the service offering ID to apply to the virtual machine', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.scaleVirtualmachine'), 'applyReason', 'text', '', 1, 0, 0, 3, '申请理由', '申请理由', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);


PROMPT 初始化添加卷属性


INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newVolume'), 'virtualmachineid', 'text', '', 1, 1, 0, 1, '虚机', 'vm id', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newVolume'), 'name', 'text', '', 1, 0, 1, 2, '卷名称', '卷名称', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newVolume'), 'diskOfferingId', 'enum', '', 1, 1, 1, 4, '数据磁盘方案', '磁盘方案', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newVolume'), 'diskSize', 'int', '', 0, 0, 1, 5, '磁盘大小(GB)', '磁盘大小(GB)', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newVolume'), 'applyReason', 'text', '', 1, 0, 0, 6, '申请理由', '申请理由', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);


INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newVolume'), 'iscustomized', 'int', '', 0, 0, 0, 7, '是否自定义磁盘大小', '是否自定义磁盘大小', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,0);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.newVolume'), 'projectid', 'text', '', 0, 0, 0, 8, '项目ID', '项目ID', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,0);



PROMPT 初始化X86物理资源申请属性
INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.X86PhysicalResourcesApplication'), 'operatingSystem', 'text', '', 1, 0, 1, 1, '操作系统', '操作系统', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.X86PhysicalResourcesApplication'), 'resourcePoolId', 'enum', '', 1, 1, 1, 2, '一级资源池', '一级资源池', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.X86PhysicalResourcesApplication'), 'cpu', 'int', '', 1, 0, 1, 3, 'CPU核数', 'CPU核数', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.X86PhysicalResourcesApplication'), 'memory', 'int', '', 1, 0, 1, 4, '内存(MB)', '内存(MB)', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.X86PhysicalResourcesApplication'), 'unit', 'int', '', 1, 0, 1, 5, '台数', '台数', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.X86PhysicalResourcesApplication'), 'description', 'text', '', 1, 0, 1, 6, '说明', '说明', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,0);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.X86PhysicalResourcesApplication'), 'applyReason', 'text', '', 1, 0, 1, 7, '申请理由', '申请理由', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);



PROMPT 初始化HP小型机资源申请属性
INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.HPMinicomputerResourcesApplication'), 'operatingSystem', 'text', '', 1, 0, 1, 1, '操作系统', '操作系统', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.HPMinicomputerResourcesApplication'), 'resourcePoolId', 'enum', '', 1, 1, 1, 2, '一级资源池', '一级资源池', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.HPMinicomputerResourcesApplication'), 'cpu', 'int', '', 1, 0, 1, 3, 'CPU核数', 'CPU核数', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.HPMinicomputerResourcesApplication'), 'memory', 'int', '', 1, 0, 1, 4, '内存(MB)', '内存(MB)', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.HPMinicomputerResourcesApplication'), 'unit', 'int', '', 1, 0, 1, 5, '台数', '台数', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.HPMinicomputerResourcesApplication'), 'description', 'text', '', 1, 0, 1, 6, '说明', '说明', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,0);

INSERT INTO T_PROVISION_ATTRIBUTE (PK_PROVISION_ATTRIBUTE_ID, WORKORDER_TYPE, ATTRIBUTE_NAME, TYPE, ALIGNTO, VISIBLE, EXTERNALVALUE, EDITABLE, SEQUENCE, DESCRIPT1, DESCRIPT2, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON,REQUIRED)
VALUES (T_PROVISION_ATTRIBUTE_ID_SEQ.NEXTVAL, (SELECT DISTINCT T.CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY = 'workorder_type.HPMinicomputerResourcesApplication'), 'applyReason', 'text', '', 1, 0, 1, 7, '申请理由', '申请理由', 'admin', SYSTIMESTAMP, 'admin', SYSTIMESTAMP,1);



PROMPT 初始化审批规则表

INSERT INTO T_APPROVERULE_CONFIG(PK_APPROVERULE_CONFIG_ID,WORKORDER_TYPE,RESOURCEPOOL_ID,APPROVE_TYPE,NEG_APPROVE_DURA,LEVEL_FIR_APPROVE_ROLE,LEVEL_SEC_APPROVE_ROLE,DESCRIPT,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON)
VALUES(APP_CONFIG_ID_SEQ.NEXTVAL,(SELECT DISTINCT CONFIG_VALUE FROM APP_CONFIG WHERE CONFIG_KEY='workorder_type.newProjectapplication'),'R_02',(SELECT DISTINCT CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY ='approve_type.auto_approval'),NULL,'admin','','','admin',SYSTIMESTAMP, 'admin', SYSTIMESTAMP);

INSERT INTO T_APPROVERULE_CONFIG(PK_APPROVERULE_CONFIG_ID,WORKORDER_TYPE,RESOURCEPOOL_ID,APPROVE_TYPE,NEG_APPROVE_DURA,LEVEL_FIR_APPROVE_ROLE,LEVEL_SEC_APPROVE_ROLE,DESCRIPT,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON)
VALUES(APP_CONFIG_ID_SEQ.NEXTVAL,(SELECT DISTINCT CONFIG_VALUE FROM APP_CONFIG WHERE CONFIG_KEY='workorder_type.deployVirtualMachine'),'R_02',(SELECT DISTINCT CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY ='approve_type.auto_approval'),NULL,'admin','','','admin',SYSTIMESTAMP, 'admin', SYSTIMESTAMP);

INSERT INTO T_APPROVERULE_CONFIG(PK_APPROVERULE_CONFIG_ID,WORKORDER_TYPE,RESOURCEPOOL_ID,APPROVE_TYPE,NEG_APPROVE_DURA,LEVEL_FIR_APPROVE_ROLE,LEVEL_SEC_APPROVE_ROLE,DESCRIPT,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON)
VALUES(APP_CONFIG_ID_SEQ.NEXTVAL,(SELECT DISTINCT CONFIG_VALUE FROM APP_CONFIG WHERE CONFIG_KEY='workorder_type.newVolume'),'R_02',(SELECT DISTINCT CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY ='approve_type.auto_approval'),NULL,'admin','','','admin',SYSTIMESTAMP, 'admin', SYSTIMESTAMP);


INSERT INTO T_APPROVERULE_CONFIG(PK_APPROVERULE_CONFIG_ID,WORKORDER_TYPE,RESOURCEPOOL_ID,APPROVE_TYPE,NEG_APPROVE_DURA,LEVEL_FIR_APPROVE_ROLE,LEVEL_SEC_APPROVE_ROLE,DESCRIPT,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON)
VALUES(APP_CONFIG_ID_SEQ.NEXTVAL,(SELECT DISTINCT CONFIG_VALUE FROM APP_CONFIG WHERE CONFIG_KEY='workorder_type.scaleVirtualmachine'),'R_02',(SELECT DISTINCT CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY ='approve_type.auto_approval'),NULL,'admin','','','admin',SYSTIMESTAMP, 'admin', SYSTIMESTAMP);

INSERT INTO T_APPROVERULE_CONFIG(PK_APPROVERULE_CONFIG_ID,WORKORDER_TYPE,RESOURCEPOOL_ID,APPROVE_TYPE,NEG_APPROVE_DURA,LEVEL_FIR_APPROVE_ROLE,LEVEL_SEC_APPROVE_ROLE,DESCRIPT,CREATED_BY,CREATED_ON,MODIFIED_BY,MODIFIED_ON)
VALUES(APP_CONFIG_ID_SEQ.NEXTVAL,(SELECT DISTINCT CONFIG_VALUE FROM APP_CONFIG WHERE CONFIG_KEY='workorder_type.projectLimitapplication'),'R_02',(SELECT DISTINCT CONFIG_VALUE FROM APP_CONFIG T WHERE T.CONFIG_KEY ='approve_type.auto_approval'),NULL,'admin','','','admin',SYSTIMESTAMP, 'admin', SYSTIMESTAMP);




commit;

SPOOL OFF
